// GENERATED by `npm run build:api` from functions/room.ts. Do not edit.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// functions/feedback.ts
var feedback_exports = {};
__export(feedback_exports, {
  default: () => handler
});
module.exports = __toCommonJS(feedback_exports);

// shared/feedback.ts
var import_node_crypto = require("node:crypto");
var FEEDBACK_TAGS = ["narrator", "voting", "bots", "rooms", "looks", "bugs", "ideas"];
var CONTEXT_KEYS = ["room", "phase", "round", "mode", "voteStyle", "visibility", "players", "bots", "isHost", "narrator", "screen", "viewport", "touch", "version"];
var MAX_TEXT = 2e3;
var PER_PERSON_PER_HOUR = 6;
var ALL_PER_HOUR = 800;
var hash = (s) => (0, import_node_crypto.createHash)("sha256").update(s).digest("hex").slice(0, 10);
function cleanContext(raw) {
  const out = {};
  if (!raw || typeof raw !== "object") return out;
  for (const k of CONTEXT_KEYS) {
    const v = raw[k];
    if (typeof v === "string") out[k] = v.slice(0, 40);
    else if (typeof v === "number" && Number.isFinite(v)) out[k] = v;
    else if (typeof v === "boolean") out[k] = v;
  }
  return out;
}
async function submitFeedback(store, input, now = Date.now()) {
  if (!input || typeof input !== "object") return { ok: false, error: "Bad request.", status: 400 };
  if (input.website) return { ok: true, id: "ignored" };
  const text = typeof input.text === "string" ? input.text.replace(/\r\n/g, "\n").trim().slice(0, MAX_TEXT) : "";
  const ratingRaw = Number(input.rating);
  const rating = Number.isInteger(ratingRaw) && ratingRaw >= 1 && ratingRaw <= 5 ? ratingRaw : null;
  if (!text && rating === null) return { ok: false, error: "Write a few words or pick a rating.", status: 400 };
  const tags = Array.isArray(input.tags) ? [...new Set(input.tags)].filter((t) => FEEDBACK_TAGS.includes(t)) : [];
  const who = hash(typeof input.token === "string" && input.token ? input.token : "anonymous");
  if (await store.hit(`fb:who:${who}`, 3600) > PER_PERSON_PER_HOUR) {
    return { ok: false, error: "Thanks, you have sent a lot already. Please try again in a while.", status: 429 };
  }
  if (await store.hit("fb:all", 3600) > ALL_PER_HOUR) return { ok: false, error: "Feedback is busy right now. Please try again later.", status: 429 };
  const item = {
    id: `${now.toString(36)}-${hash(`${who}${now}${Math.random()}`).slice(0, 6)}`,
    at: now,
    text,
    rating,
    tags,
    who,
    context: cleanContext(input.context)
  };
  await store.pushFeedback(item);
  return { ok: true, id: item.id };
}
function isAdmin(authHeader, adminKey) {
  if (!adminKey || adminKey.length < 12) return false;
  const given = (authHeader ?? "").replace(/^Bearer\s+/i, "");
  const a = Buffer.from(hash(given));
  const b = Buffer.from(hash(adminKey));
  return a.length === b.length && (0, import_node_crypto.timingSafeEqual)(a, b);
}
async function listFeedback(store, limit = 500) {
  return (await store.listFeedback(Math.min(Math.max(limit, 1), 2e3))).sort((a, b) => b.at - a.at);
}
var csvCell = (v) => `"${String(v ?? "").replace(/"/g, '""')}"`;
function toCsv(items) {
  const head = ["id", "at_iso", "rating", "tags", "text", "who", "context_json"];
  const rows = items.map((i) => [i.id, new Date(i.at).toISOString(), i.rating ?? "", i.tags.join("|"), i.text, i.who, JSON.stringify(i.context)].map(csvCell).join(","));
  return [head.join(","), ...rows].join("\n");
}

// shared/store.ts
var TTL_SEC = 60 * 60 * 8;
var MemoryStore = class {
  rooms = /* @__PURE__ */ new Map();
  listed = /* @__PURE__ */ new Set();
  feedback = [];
  hits = /* @__PURE__ */ new Map();
  chains = /* @__PURE__ */ new Map();
  async get(code) {
    const raw = this.rooms.get(code);
    return raw ? JSON.parse(raw) : null;
  }
  async set(code, room) {
    this.rooms.set(code, JSON.stringify(room));
  }
  async pushFeedback(item) {
    this.feedback.push(item);
  }
  async listFeedback(limit) {
    return this.feedback.slice(-limit);
  }
  async hit(key, windowSec) {
    const now = Date.now();
    const cur = this.hits.get(key);
    const rec = cur && cur.until > now ? cur : { n: 0, until: now + windowSec * 1e3 };
    rec.n += 1;
    this.hits.set(key, rec);
    return rec.n;
  }
  async index(code, listed) {
    if (listed) this.listed.add(code);
    else this.listed.delete(code);
  }
  async openCodes() {
    return [...this.listed];
  }
  async getMany(codes) {
    return Promise.all(codes.map((c) => this.get(c)));
  }
  async lock(code) {
    const prev = this.chains.get(code) ?? Promise.resolve();
    let release;
    const next = new Promise((res) => release = res);
    this.chains.set(code, prev.then(() => next));
    await prev;
    return async () => release();
  }
};
var RedisStore = class {
  constructor(url, token) {
    this.url = url;
    this.token = token;
  }
  url;
  token;
  async cmd(...args) {
    const res = await fetch(this.url, {
      method: "POST",
      headers: { Authorization: `Bearer ${this.token}`, "Content-Type": "application/json" },
      body: JSON.stringify(args)
    });
    if (!res.ok) throw new Error(`Redis ${res.status}`);
    return (await res.json()).result;
  }
  async get(code) {
    const raw = await this.cmd("GET", `mgm:room:${code}`);
    return raw ? JSON.parse(raw) : null;
  }
  async set(code, room) {
    await this.cmd("SET", `mgm:room:${code}`, JSON.stringify(room), "EX", TTL_SEC);
  }
  async pushFeedback(item) {
    await this.cmd("RPUSH", "mgm:feedback", JSON.stringify(item));
    await this.cmd("LTRIM", "mgm:feedback", -2e4, -1);
  }
  async listFeedback(limit) {
    const raws = await this.cmd("LRANGE", "mgm:feedback", -limit, -1) ?? [];
    return raws.map((r) => JSON.parse(r));
  }
  async hit(key, windowSec) {
    const n = await this.cmd("INCR", `mgm:hit:${key}`);
    if (n === 1) await this.cmd("EXPIRE", `mgm:hit:${key}`, windowSec);
    return n;
  }
  async index(code, listed) {
    await this.cmd(listed ? "SADD" : "SREM", "mgm:open", code);
  }
  async openCodes() {
    return await this.cmd("SMEMBERS", "mgm:open") ?? [];
  }
  async getMany(codes) {
    if (!codes.length) return [];
    const raws = await this.cmd("MGET", ...codes.map((c) => `mgm:room:${c}`));
    return raws.map((r) => r ? JSON.parse(r) : null);
  }
  async lock(code) {
    const key = `mgm:lock:${code}`;
    const id = Math.random().toString(36).slice(2);
    for (let i = 0; i < 40; i++) {
      const got = await this.cmd("SET", key, id, "NX", "PX", 4e3);
      if (got === "OK") {
        return async () => {
          const cur = await this.cmd("GET", key);
          if (cur === id) await this.cmd("DEL", key);
        };
      }
      await new Promise((r) => setTimeout(r, 60));
    }
    throw new Error("Room is busy, try again.");
  }
};
var shared = null;
function defaultStore() {
  if (shared) return shared;
  const url = process.env.UPSTASH_REDIS_REST_URL ?? process.env.KV_REST_API_URL;
  const token = process.env.UPSTASH_REDIS_REST_TOKEN ?? process.env.KV_REST_API_TOKEN;
  shared = url && token ? new RedisStore(url, token) : new MemoryStore();
  return shared;
}

// functions/feedback.ts
async function handler(req, res) {
  res.setHeader("Cache-Control", "no-store");
  try {
    const store = defaultStore();
    if (req.method === "POST") {
      const out = await submitFeedback(store, req.body);
      return res.status(out.ok ? 200 : out.status).json(out);
    }
    if (req.method === "GET") {
      if (!isAdmin(req.headers.authorization, process.env.FEEDBACK_ADMIN_KEY)) return res.status(403).json({ ok: false, error: "Not allowed." });
      const items = await listFeedback(store, Number(req.query.limit) || 500);
      if (req.query.format === "csv") {
        res.setHeader("Content-Type", "text/csv; charset=utf-8");
        return res.status(200).send(toCsv(items));
      }
      return res.status(200).json({ ok: true, items });
    }
    return res.status(405).json({ ok: false, error: "Use POST or GET." });
  } catch (e) {
    return res.status(500).json({ ok: false, error: e instanceof Error ? e.message : "Server error." });
  }
}
module.exports = module.exports.default;
