// GENERATED by `npm run build:api` from functions/room.ts. Do not edit.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// functions/room.ts
var room_exports = {};
__export(room_exports, {
  default: () => handler
});
module.exports = __toCommonJS(room_exports);

// shared/game.ts
var DEFAULT_SETTINGS = {
  mode: "table",
  doctorSelfSave: true,
  doctorRepeatSave: true,
  useDoctor: true,
  useDetective: true,
  mafiaCount: null,
  revealRoleOnDeath: false,
  deadSeeRoles: false,
  dayTimerSec: 180,
  voteTimerSec: 60,
  voteStyle: "trial",
  defenseSec: 30,
  visibility: "private",
  roomName: ""
};
var clampN = (n, lo, hi, fallback) => Number.isFinite(n) ? Math.min(hi, Math.max(lo, Math.round(n))) : fallback;
function normalizeSettings(input) {
  const d = DEFAULT_SETTINGS;
  const raw = input ?? {};
  const oneOf = (v, allowed, fallback) => allowed.includes(v) ? v : fallback;
  const bool = (v, fallback) => typeof v === "boolean" ? v : fallback;
  return {
    mode: oneOf(raw.mode, ["table", "phones", "remote"], d.mode),
    doctorSelfSave: bool(raw.doctorSelfSave, d.doctorSelfSave),
    doctorRepeatSave: bool(raw.doctorRepeatSave, d.doctorRepeatSave),
    useDoctor: bool(raw.useDoctor, d.useDoctor),
    useDetective: bool(raw.useDetective, d.useDetective),
    mafiaCount: raw.mafiaCount == null ? null : clampN(Number(raw.mafiaCount), 1, 9, 1),
    revealRoleOnDeath: bool(raw.revealRoleOnDeath, d.revealRoleOnDeath),
    deadSeeRoles: bool(raw.deadSeeRoles, d.deadSeeRoles),
    dayTimerSec: clampN(Number(raw.dayTimerSec ?? d.dayTimerSec), 30, 900, d.dayTimerSec),
    voteTimerSec: clampN(Number(raw.voteTimerSec ?? d.voteTimerSec), 15, 300, d.voteTimerSec),
    voteStyle: oneOf(raw.voteStyle, ["trial", "quick"], d.voteStyle),
    defenseSec: clampN(Number(raw.defenseSec ?? d.defenseSec), 15, 120, d.defenseSec),
    visibility: oneOf(raw.visibility, ["open", "ask", "private"], d.visibility),
    roomName: String(raw.roomName ?? d.roomName).replace(/\s+/g, " ").trim().slice(0, 30)
  };
}
var MIN_PLAYERS = 4;
var MAX_PLAYERS = 20;
var BOT_NAMES = [
  "Maya",
  "Theo",
  "Isla",
  "Dev",
  "Nora",
  "Sam",
  "Zoe",
  "Kai",
  "Lila",
  "Omar",
  "Ruby",
  "Finn",
  "Anika",
  "Leo",
  "June",
  "Marco",
  "Tess",
  "Ali",
  "Cleo",
  "Jules"
];
var PERSONAS = ["warm", "blunt", "playful"];
var ok = (value) => ({ ok: true, value });
var fail = (error) => ({ ok: false, error });
function roleCounts(n, s) {
  const maxMafia = Math.max(1, Math.ceil(n / 2) - 1);
  const auto = Math.max(1, Math.floor(n / 3));
  const mafia = Math.min(maxMafia, Math.max(1, s.mafiaCount ?? auto));
  const doctor = s.useDoctor && n - mafia >= 2 ? 1 : 0;
  const detective = s.useDetective && n - mafia - doctor >= 1 ? 1 : 0;
  const villager = n - mafia - doctor - detective;
  return { mafia, doctor, detective, villager };
}
function shuffle(items, rng) {
  const a = [...items];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
var Game = class _Game {
  constructor(rng = Math.random) {
    this.rng = rng;
  }
  rng;
  phase = "lobby";
  round = 0;
  settings = { ...DEFAULT_SETTINGS };
  players = [];
  hostId = null;
  winner = null;
  lines = [];
  talk = [];
  talkSeq = 0;
  pending = [];
  declined = [];
  blocked = [];
  notes = {};
  // night
  steps = [];
  stepIdx = 0;
  mafiaPicks = {};
  doctorPick = null;
  detectivePick = null;
  lastSaved = null;
  // day
  votes = {};
  // voterId -> targetId | "skip"
  voteStage = "final";
  defendants = [];
  defenseIdx = 0;
  lastResult = null;
  lastNightDeathId = null;
  seq = 0;
  /** Load a saved game. Rooms outlive deploys, so anything saved by older code is upgraded to the current shape. */
  static fromJSON(data, rng = Math.random) {
    const g = Object.assign(new _Game(rng), structuredClone(data));
    g.settings = normalizeSettings(g.settings);
    for (const k of ["players", "lines", "talk", "pending", "declined", "blocked", "defendants", "steps"]) {
      if (!Array.isArray(g[k])) g[k] = [];
    }
    for (const k of ["notes", "votes", "mafiaPicks"]) {
      if (!g[k] || typeof g[k] !== "object") g[k] = {};
    }
    if (g.voteStage !== "poll" && g.voteStage !== "final") g.voteStage = "final";
    return g;
  }
  toJSON() {
    const { rng: _rng, ...state } = this;
    return state;
  }
  // ---------- helpers ----------
  player(id) {
    return this.players.find((p) => p.id === id);
  }
  alive(role) {
    return this.players.filter((p) => p.alive && (!role || p.role === role));
  }
  narrate(text, cue = null) {
    this.lines.push({ seq: ++this.seq, text, cue });
    if (this.lines.length > 40) this.lines.shift();
  }
  pick(options) {
    return options[Math.floor(this.rng() * options.length)];
  }
  classic() {
    return this.settings.mode !== "remote";
  }
  get step() {
    return this.phase === "night" ? this.steps[this.stepIdx] ?? null : null;
  }
  // ---------- lobby ----------
  addPlayer(id, name) {
    const existing = this.player(id);
    if (existing) {
      existing.connected = true;
      return ok();
    }
    if (this.blocked.includes(id)) return fail("You were removed from this room.");
    if (this.phase !== "lobby") return fail("The game has already started.");
    const clean = name.trim().slice(0, 16);
    if (!clean) return fail("Enter a name.");
    if (this.players.length >= MAX_PLAYERS) return fail("The room is full.");
    if (this.players.some((p) => p.name.toLowerCase() === clean.toLowerCase())) return fail("That name is taken.");
    this.players.push({ id, name: clean, role: null, alive: true, connected: true, seenRole: false });
    this.hostId ??= id;
    return ok();
  }
  removePlayer(id) {
    this.pending = this.pending.filter((p) => p.id !== id);
    if (!this.player(id)) return ok();
    if (this.phase !== "lobby") return fail("Players can only leave from the lobby.");
    this.players = this.players.filter((p) => p.id !== id);
    if (this.hostId === id) this.hostId = this.players.find((p) => p.connected && !p.bot)?.id ?? this.players.find((p) => !p.bot)?.id ?? null;
    return ok();
  }
  /** Ask to join (rooms set to "Ask to join"). The host answers with admit or decline. */
  requestJoin(id, name) {
    if (this.player(id)) return ok();
    if (this.blocked.includes(id)) return fail("You were removed from this room.");
    if (this.phase !== "lobby") return fail("The game has already started.");
    const clean = name.trim().slice(0, 16);
    if (!clean) return fail("Enter a name.");
    if (this.players.some((p) => p.name.toLowerCase() === clean.toLowerCase())) return fail("That name is taken.");
    this.declined = this.declined.filter((d) => d !== id);
    this.pending = this.pending.filter((p) => p.id !== id);
    if (this.pending.length >= 10) return fail("Too many people are waiting. Try again soon.");
    this.pending.push({ id, name: clean });
    return ok();
  }
  admit(id) {
    const req = this.pending.find((p) => p.id === id);
    if (!req) return fail("That request is gone.");
    this.pending = this.pending.filter((p) => p.id !== id);
    return this.addPlayer(req.id, req.name);
  }
  decline(id) {
    this.pending = this.pending.filter((p) => p.id !== id);
    if (!this.declined.includes(id)) this.declined.push(id);
    return ok();
  }
  /** Remove a person and stop them rejoining this room. */
  kick(id) {
    if (this.phase !== "lobby") return fail("People can only be removed from the lobby.");
    const p = this.player(id);
    if (!p || p.bot) return fail("That player cannot be removed.");
    if (id === this.hostId) return fail("The host cannot be removed.");
    this.players = this.players.filter((q) => q.id !== id);
    if (!this.blocked.includes(id)) this.blocked.push(id);
    return ok();
  }
  addBot() {
    if (this.phase !== "lobby") return fail("Bots can only join from the lobby.");
    if (this.players.length >= MAX_PLAYERS) return fail("The room is full.");
    const taken = new Set(this.players.map((p) => p.name.toLowerCase()));
    const free = BOT_NAMES.filter((n) => !taken.has(n.toLowerCase()));
    if (!free.length) return fail("No bot names left.");
    const name = this.pick(free);
    const bots = this.players.filter((p) => p.bot).length;
    this.players.push({
      id: `bot-${name.toLowerCase()}`,
      name,
      bot: true,
      persona: PERSONAS[bots % PERSONAS.length],
      role: null,
      alive: true,
      connected: true,
      seenRole: false
    });
    return ok();
  }
  /** A line in the table-talk feed, from a person or a bot. */
  say(playerId, text) {
    const me = this.player(playerId);
    if (!me?.alive) return fail("Only living players can talk.");
    if (!["day", "vote", "defense", "dawn"].includes(this.phase)) return fail("Wait for the day to talk.");
    const clean = text.replace(/\s+/g, " ").trim().slice(0, 140);
    if (!clean) return fail("Type something to say.");
    this.talk.push({ seq: ++this.talkSeq, id: me.id, name: me.name, text: clean, bot: !!me.bot });
    if (this.talk.length > 40) this.talk.shift();
    return ok();
  }
  setConnected(id, connected) {
    const p = this.player(id);
    if (p) p.connected = connected;
    if (!connected && this.hostId === id) {
      const next = this.players.find((q) => q.connected && !q.bot && q.id !== id);
      if (next) this.hostId = next.id;
    }
  }
  updateSettings(patch) {
    if (this.phase !== "lobby") return fail("Settings are locked once the game starts.");
    const bad = (v, allowed) => v !== void 0 && !allowed.includes(v);
    if (bad(patch.mode, ["table", "phones", "remote"])) return fail("Unknown mode.");
    if (bad(patch.voteStyle, ["trial", "quick"])) return fail("Unknown voting style.");
    if (bad(patch.visibility, ["open", "ask", "private"])) return fail("Unknown room visibility.");
    this.settings = normalizeSettings({ ...this.settings, ...patch });
    return ok();
  }
  start() {
    if (this.phase !== "lobby") return fail("The game has already started.");
    const n = this.players.length;
    if (n < MIN_PLAYERS) return fail(`You need at least ${MIN_PLAYERS} players.`);
    const c = roleCounts(n, this.settings);
    const deck = [
      ...Array(c.mafia).fill("mafia"),
      ...Array(c.doctor).fill("doctor"),
      ...Array(c.detective).fill("detective"),
      ...Array(c.villager).fill("villager")
    ];
    shuffle(deck, this.rng).forEach((role, i) => {
      const p = this.players[i];
      p.role = role;
      p.alive = true;
      p.seenRole = false;
    });
    this.notes = {};
    this.winner = null;
    this.round = 0;
    this.lastSaved = null;
    this.lines = [];
    this.phase = "reveal";
    this.narrate("Look at your phone. | Your role is for your eyes only. || Keep it secret.", "deal");
    return ok();
  }
  // ---------- role reveal ----------
  ackRole(id) {
    if (this.phase !== "reveal") return fail("Not time to confirm roles.");
    const p = this.player(id);
    if (!p) return fail("Unknown player.");
    p.seenRole = true;
    return ok();
  }
  revealComplete() {
    return this.phase === "reveal" && this.players.every((p) => p.seenRole || !p.connected);
  }
  // ---------- night ----------
  beginNight() {
    this.round += 1;
    this.phase = "night";
    this.steps = ["mafia"];
    if (this.players.some((p) => p.role === "doctor")) this.steps.push("doctor");
    if (this.players.some((p) => p.role === "detective")) this.steps.push("detective");
    this.stepIdx = 0;
    this.mafiaPicks = {};
    this.doctorPick = null;
    this.detectivePick = null;
    this.votes = {};
    this.talk = [];
    this.lastResult = null;
    this.narrate(
      this.classic() ? this.pick([
        "Night falls on the village. || Everyone... close your eyes. | Keep them closed. | No peeking.",
        "The sun sets... | and the village falls silent. || Everyone, close your eyes.",
        "Darkness settles over the village. || Close your eyes, everyone. | Do not open them until I say so."
      ]) : "Night falls on the village. | Night roles, check your phones.",
      "night"
    );
    this.announceStep(null);
  }
  announceStep(prev) {
    const step = this.steps[this.stepIdx];
    const label = { mafia: "Mafia", doctor: "Doctor", detective: "Detective" };
    const open = {
      mafia: [
        "Mafia... open your eyes. | Find your partners in the dark. || Choose... who will not see the morning.",
        "Mafia... wake up. | Silently agree on your victim."
      ],
      doctor: [
        "Doctor... open your eyes. | Who will you protect tonight?",
        "Doctor... wake up. | Choose someone to save from the dark."
      ],
      detective: [
        "Detective... open your eyes. | Whose secret do you wish to uncover?",
        "Detective... wake up. | Choose someone to investigate."
      ]
    };
    const remote = {
      mafia: "Mafia, it is your turn. | Agree on a victim.",
      doctor: "Doctor, it is your turn. | Choose someone to save.",
      detective: "Detective, it is your turn. | Choose someone to investigate."
    };
    if (this.classic()) {
      const close = prev ? `${label[prev]}... close your eyes. || ` : "";
      this.narrate(close + this.pick([...open[step]]), step);
    } else {
      this.narrate(remote[step], step);
    }
  }
  /** Players who must act in the current night step. */
  actors() {
    const step = this.step;
    return step ? this.alive(step) : [];
  }
  canTarget(playerId) {
    const step = this.step;
    const me = this.player(playerId);
    if (!step || !me || !me.alive || me.role !== step) return [];
    let pool = this.alive();
    if (step === "mafia") pool = pool.filter((p) => p.role !== "mafia");
    if (step === "detective") pool = pool.filter((p) => p.id !== me.id);
    if (step === "doctor") {
      if (!this.settings.doctorSelfSave) pool = pool.filter((p) => p.id !== me.id);
      if (!this.settings.doctorRepeatSave && this.lastSaved) pool = pool.filter((p) => p.id !== this.lastSaved);
    }
    return pool.map((p) => p.id);
  }
  nightAction(playerId, targetId) {
    const step = this.step;
    if (!step) return fail("It is not night.");
    const me = this.player(playerId);
    if (!me?.alive || me.role !== step) return fail("It is not your turn.");
    if (!this.canTarget(playerId).includes(targetId)) return fail("You cannot choose that player.");
    if (step === "mafia") this.mafiaPicks[playerId] = targetId;
    if (step === "doctor") this.doctorPick = targetId;
    if (step === "detective") {
      if (this.detectivePick) return fail("You already investigated tonight.");
      this.detectivePick = targetId;
      const target = this.player(targetId);
      (this.notes[playerId] ??= []).push({ night: this.round, targetId, isMafia: target.role === "mafia" });
    }
    return ok();
  }
  /** True when no one is left to act, so the server should skip the step quietly. */
  stepIsEmpty() {
    return this.step !== null && this.actors().length === 0;
  }
  stepComplete() {
    const step = this.step;
    if (!step) return false;
    if (this.stepIsEmpty()) return true;
    if (step === "mafia") {
      const mafia = this.actors();
      const picks = mafia.map((m) => this.mafiaPicks[m.id]);
      return picks.every(Boolean) && new Set(picks).size === 1;
    }
    if (step === "doctor") return this.doctorPick !== null;
    return this.detectivePick !== null;
  }
  /** Move to the next night step, or resolve the night. `force` settles missing picks. */
  advanceNight(force = false) {
    const step = this.step;
    if (!step) return;
    if (!force && !this.stepComplete()) return;
    this.stepIdx += 1;
    if (this.stepIdx < this.steps.length) {
      this.announceStep(step);
    } else {
      if (this.classic()) this.narrate(`${{ mafia: "Mafia", doctor: "Doctor", detective: "Detective" }[step]}... close your eyes.`, "night");
      this.resolveNight();
    }
  }
  mafiaTarget() {
    const tally = /* @__PURE__ */ new Map();
    for (const m of this.alive("mafia")) {
      const t = this.mafiaPicks[m.id];
      if (t) tally.set(t, (tally.get(t) ?? 0) + 1);
    }
    if (!tally.size) return null;
    const top = Math.max(...tally.values());
    const tied = [...tally].filter(([, n]) => n === top).map(([id]) => id).sort();
    return tied[Math.floor(this.rng() * tied.length)];
  }
  resolveNight() {
    const target = this.mafiaTarget();
    const saved = target !== null && target === this.doctorPick;
    this.lastSaved = this.doctorPick;
    const victim = target && !saved ? this.player(target) : null;
    if (victim) victim.alive = false;
    this.lastNightDeathId = victim?.id ?? null;
    this.phase = "dawn";
    const open = this.classic() ? "The sun rises. || Everyone... open your eyes. || " : "The sun rises. || ";
    const role = victim && this.settings.revealRoleOnDeath ? ` | They were ${article(victim.role)}.` : "";
    this.narrate(
      open + (victim ? `Sadly... | ${victim.name} | was killed in the night.${role}` : this.pick(["And miraculously... | nobody died tonight.", "The village wakes... | and everyone is still alive."])),
      victim ? "dawn-death" : "dawn"
    );
    this.checkWin();
  }
  // ---------- day ----------
  startDay() {
    if (this.phase !== "dawn") return;
    this.phase = "day";
    this.narrate(`The village gathers. | Someone among you is lying. || Discuss. | You have ${spoken(this.settings.dayTimerSec)}.`, "day");
  }
  startVote() {
    if (this.phase !== "day") return;
    this.phase = "vote";
    this.votes = {};
    this.defendants = [];
    this.defenseIdx = 0;
    if (this.settings.voteStyle === "trial") {
      this.voteStage = "poll";
      this.narrate("Time is up. || Who do you suspect? | Cast your first vote. | It only decides who must defend themselves.", "vote");
    } else {
      this.voteStage = "final";
      this.narrate("Time is up. || Point at the one you suspect... | and cast your vote.", "vote");
    }
  }
  castVote(playerId, targetId) {
    if (this.phase !== "vote") return fail("Voting is not open.");
    const me = this.player(playerId);
    if (!me?.alive) return fail("Only living players can vote.");
    if (targetId !== "skip") {
      const t = this.player(targetId);
      if (!t?.alive) return fail("Pick a living player.");
      if (t.id === me.id) return fail("You cannot vote for yourself.");
      if (this.voteStage === "final" && this.defendants.length && !this.defendants.includes(t.id)) {
        return fail("Vote for one of the accused, or skip.");
      }
    }
    this.votes[playerId] = targetId;
    return ok();
  }
  voteComplete() {
    return this.phase === "vote" && this.alive().every((p) => this.votes[p.id]);
  }
  tally() {
    const counts = {};
    for (const t of Object.values(this.votes)) counts[t] = (counts[t] ?? 0) + 1;
    return counts;
  }
  /** Token for the current wait. A stale tap on "skip" names an old token and does nothing. */
  skipToken() {
    return `${this.phase}:${this.round}:${this.voteStage}:${this.defenseIdx}`;
  }
  /** Close the current vote. In trial style the first vote picks defendants; the final vote eliminates. */
  resolveVote() {
    if (this.phase !== "vote") return;
    if (this.voteStage === "poll") return this.resolvePoll();
    const counts = this.tally();
    const entries = Object.entries(counts);
    const top = entries.length ? Math.max(...entries.map(([, n]) => n)) : 0;
    const leaders = entries.filter(([, n]) => n === top).map(([id]) => id);
    let eliminated = null;
    let text;
    if (leaders.length !== 1 || leaders[0] === "skip") {
      text = leaders.length > 1 ? "The village is divided. | Nobody is eliminated." : "The village chooses to wait. | Nobody is eliminated.";
    } else {
      eliminated = this.player(leaders[0]);
      eliminated.alive = false;
      const role = this.settings.revealRoleOnDeath ? ` || They were ${article(eliminated.role)}.` : "";
      text = `${eliminated.name}... | the village has spoken. || You are eliminated, with ${top} vote${top === 1 ? "" : "s"}.${role}`;
    }
    this.lastResult = { text, eliminatedId: eliminated?.id ?? null };
    this.phase = "result";
    this.narrate(text, eliminated ? "elim" : "noelim");
    this.checkWin();
  }
  resolvePoll() {
    const counts = this.tally();
    const skips = counts.skip ?? 0;
    const ranked = Object.entries(counts).filter(([id]) => id !== "skip").sort((a, b) => b[1] - a[1]);
    if (!ranked.length || ranked[0][1] <= skips) {
      this.lastResult = { text: "The village cannot agree on anyone. | Nobody is accused.", eliminatedId: null };
      this.phase = "result";
      this.narrate(this.lastResult.text, "noelim");
      return;
    }
    const chosen = [];
    const groups = /* @__PURE__ */ new Map();
    for (const [id, n] of ranked) groups.set(n, [...groups.get(n) ?? [], id]);
    for (const n of [...groups.keys()].sort((a, b) => b - a)) {
      const ids = shuffle(groups.get(n), this.rng);
      for (const id of ids) if (chosen.length < 2) chosen.push(id);
      if (chosen.length >= 2) break;
    }
    this.defendants = chosen;
    this.defenseIdx = 0;
    this.phase = "defense";
    const names = chosen.map((id) => this.player(id).name);
    const intro = names.length === 2 ? `${names[0]}... | and ${names[1]}. || You stand accused.` : `${names[0]}... | you stand accused.`;
    this.narrate(`The first votes are in. || ${intro} || ${this.defenseCall(0)}`, "defense");
  }
  defenseCall(i) {
    const name = this.player(this.defendants[i]).name;
    const t = spoken(this.settings.defenseSec);
    return i === 0 ? `${name}... | the floor is yours. | You have ${t} to defend yourself.` : `Now... | ${name}. | Your turn. | You have ${t} to defend yourself.`;
  }
  /** Move to the next defender, or to the final vote after the last one. */
  advanceDefense() {
    if (this.phase !== "defense") return;
    if (this.defenseIdx + 1 < this.defendants.length) {
      this.defenseIdx += 1;
      this.narrate(this.defenseCall(this.defenseIdx), "defense");
      return;
    }
    this.phase = "vote";
    this.voteStage = "final";
    this.votes = {};
    this.narrate("The defenses are done. || Now... | cast your final vote. | Who will be eliminated?", "final");
  }
  // ---------- end ----------
  checkWin() {
    const mafia = this.alive("mafia").length;
    const town = this.alive().length - mafia;
    if (mafia === 0) this.finish("town", "The last Mafia is gone. || The Town wins!", "win-town");
    else if (mafia >= town) this.finish("mafia", "Darkness settles over the village for good. || The Mafia wins.", "win-mafia");
  }
  finish(w, text, cue) {
    this.winner = w;
    this.phase = "over";
    this.narrate(text, cue);
  }
  rematch() {
    if (this.phase !== "over") return fail("The game is not over.");
    this.phase = "lobby";
    this.round = 0;
    this.winner = null;
    this.notes = {};
    this.lines = [];
    this.talk = [];
    this.lastResult = null;
    this.defendants = [];
    this.defenseIdx = 0;
    this.voteStage = "final";
    for (const p of this.players) {
      p.role = null;
      p.alive = true;
      p.seenRole = false;
    }
    this.players = this.players.filter((p) => p.connected);
    return ok();
  }
  // ---------- views ----------
  /** What a given player (or the shared table screen, when null) may know. */
  viewFor(playerId) {
    const me = this.player(playerId);
    const over = this.phase === "over";
    const seeAll = over || me && !me.alive && this.settings.deadSeeRoles;
    const showRole = (p) => seeAll || p.id === me?.id || me?.role === "mafia" && p.role === "mafia" || !p.alive && this.settings.revealRoleOnDeath;
    const counts = this.phase === "vote" || this.phase === "defense" || this.phase === "result" ? this.tally() : {};
    const step = this.step;
    return {
      phase: this.phase,
      round: this.round,
      settings: this.settings,
      hostId: this.hostId,
      winner: this.winner,
      lines: this.lines.slice(-12),
      talk: this.talk.slice(-14),
      joinStatus: me ? null : playerId ? this.blocked.includes(playerId) ? "blocked" : this.pending.some((p) => p.id === playerId) ? "pending" : this.declined.includes(playerId) ? "declined" : null : null,
      pending: playerId && playerId === this.hostId ? this.pending : [],
      players: this.players.map((p) => ({
        id: p.id,
        name: p.name,
        alive: p.alive,
        connected: p.connected,
        seenRole: p.seenRole,
        bot: !!p.bot,
        role: this.phase === "lobby" ? null : showRole(p) ? p.role : null
      })),
      you: me ? {
        id: me.id,
        name: me.name,
        role: me.role,
        alive: me.alive,
        isHost: me.id === this.hostId,
        notes: this.notes[me.id] ?? []
      } : null,
      night: {
        step: this.phase === "night" ? step : null,
        yourTargets: me ? this.canTarget(me.id) : [],
        yourPick: me?.role === "mafia" ? this.mafiaPicks[me.id] ?? null : me?.role === "doctor" ? this.doctorPick : me?.role === "detective" ? this.detectivePick : null,
        mafiaPicks: me?.role === "mafia" && this.step === "mafia" ? this.mafiaPicks : {}
      },
      vote: {
        counts,
        yourVote: me ? this.votes[me.id] ?? null : null,
        stage: this.voteStage,
        voted: this.phase === "vote" ? Object.keys(this.votes).length : 0,
        eligible: this.alive().length
      },
      result: this.lastResult,
      defendants: this.defendants,
      defenseIdx: this.defenseIdx,
      skipToken: this.skipToken(),
      minPlayers: MIN_PLAYERS,
      suggested: roleCounts(Math.max(this.players.length, MIN_PLAYERS), this.settings)
    };
  }
};
function spoken(sec) {
  if (sec < 60) return `${sec} seconds`;
  const m = Math.round(sec / 60);
  return `${m} minute${m === 1 ? "" : "s"}`;
}
function article(role) {
  return role === "mafia" ? "a Mafia member" : role === "villager" ? "a Villager" : `the ${role[0].toUpperCase()}${role.slice(1)}`;
}

// shared/bots.ts
var pickOf = (xs, rng) => xs[Math.floor(rng() * xs.length)];
var LINES = {
  warm: {
    accuse: ["I don't want to point fingers, but {t} has been quiet. What do you think, {t}?", "Gut feeling... I'm a little worried about {t}.", "Can we talk about {t}? Something feels off, and I hope I'm wrong."],
    claim: ["Just so everyone knows, I'm a villager. I promise.", "I'm on your side, truly. Let's be careful with each other."],
    death: ["I'm so sorry, {v}. That's awful.", "{v} was one of the good ones. We have to be careful now."],
    reply: ["Me? I promise it isn't me, {n}. Please look somewhere else.", "Oh, that hurts. I'm just trying to help us."],
    defend: ["Please listen. I'm town, and if you vote me out the Mafia gets a free turn.", "I know it looks bad, but I'm only trying to help. Think about who pushed this."],
    vouch: ["I trust {t}. They've been straight with me."]
  },
  blunt: {
    accuse: ["{t}. Something's off with you.", "I'm voting {t}. Call it instinct.", "{t}, you've said nothing useful. Why?"],
    claim: ["Not me. Next.", "I'm town. Don't waste time on me."],
    death: ["{v} is gone. Someone here did that.", "That's what happens when we sit around. Pick a suspect."],
    reply: ["Wrong target.", "Cute. But no."],
    defend: ["I'm not Mafia. Count the votes and ask who started this.", "You're about to make a mistake. Look closer."],
    vouch: ["{t} is fine. Leave them alone."]
  },
  playful: {
    accuse: ["I'm not saying {t} is a mobster, but they do have the look of a mobster.", "{t}, you're sweating. Are you sweating?", "My spidey sense says {t}. It's usually wrong, but still."],
    claim: ["I'm an honest villager. I even return my shopping carts.", "Me, Mafia? I can't even lie about my age."],
    death: ["RIP {v}. You'll be missed. Mostly your snacks.", "Well, that escalated quickly, {v}."],
    reply: ["Whoa, who, me? I'm innocent as a bowl of pasta.", "You wound me, {n}. Deeply."],
    defend: ["Okay, okay, plot twist: I'm a villager. Please don't vote me out.", "If I were Mafia I'd have a much better poker face. Look at this face."],
    vouch: ["{t} seems cool. I'd share fries with {t}."]
  }
};
var fill = (s, vars) => s.replace(/\{(\w)\}/g, (_, k) => vars[k] ?? "");
function tasks(room, g, t) {
  const out = [];
  const bots = g.players.filter((p) => p.bot);
  const mem = room.bots;
  for (const b of bots) {
    if (g.phase === "reveal" && !b.seenRole) out.push({ id: `ack:${b.id}`, bot: b, min: t.botRevealMinMs, max: t.botRevealMaxMs });
    if (g.phase === "night" && b.alive && g.step === b.role && g.canTarget(b.id).length) {
      const mine = g.actors();
      const humansMafia = b.role === "mafia" ? mine.filter((m) => !m.bot) : [];
      const waitingOnHuman = humansMafia.length > 0 && humansMafia.every((m) => !g.mafiaPicks[m.id]);
      const already = b.role === "mafia" ? g.mafiaPicks[b.id] : b.role === "doctor" ? g.doctorPick : g.detectivePick;
      if (!waitingOnHuman && !already) out.push({ id: `night:${b.id}`, bot: b, min: t.botNightMinMs, max: t.botNightMaxMs });
    }
    if (g.phase === "vote" && b.alive && !g.votes[b.id]) {
      out.push({ id: `vote:${b.id}`, bot: b, min: t.botVoteMinMs, max: Math.min(t.botVoteMaxMs, g.settings.voteTimerSec * 600) });
    }
    if (g.phase === "day" && b.alive && (mem.done[`talk:${b.id}`] ?? 0) < 2) {
      out.push({ id: `talk:${b.id}`, bot: b, min: t.botTalkMinMs, max: Math.min(t.botTalkMaxMs, g.settings.dayTimerSec * 650) });
    }
    if (g.phase === "defense" && g.defendants[g.defenseIdx] === b.id && !(mem.done[`defend:${b.id}`] ?? 0)) {
      out.push({ id: `defend:${b.id}`, bot: b, min: t.botDefendMinMs, max: t.botDefendMaxMs });
    }
    if (["day", "vote", "defense"].includes(g.phase) && b.alive && mem.replies.includes(b.id)) {
      out.push({ id: `reply:${b.id}`, bot: b, min: t.botReplyMinMs, max: t.botReplyMaxMs });
    }
  }
  return out;
}
var keyOf = (g) => `${g.phase}:${g.round}:${g.voteStage}:${g.defenseIdx}:${g.stepIdx}`;
function syncBots(room, g) {
  const key = keyOf(g);
  if (!room.bots || room.bots.key !== key) room.bots = { key, due: {}, done: {}, replies: [] };
}
function noteMentions(room, g, speakerId, text) {
  syncBots(room, g);
  const low = text.toLowerCase();
  for (const b of g.players) {
    if (b.bot && b.alive && b.id !== speakerId && new RegExp(`\\b${b.name.toLowerCase()}\\b`).test(low) && !room.bots.replies.includes(b.id)) {
      room.bots.replies.push(b.id);
    }
  }
}
function suspects(g, bot) {
  return g.alive().filter((p) => p.id !== bot.id);
}
function chooseTarget(g, bot, pool, rng) {
  if (!pool.length) return void 0;
  if (bot.role === "detective") {
    const found = pool.find((p) => (g.notes[bot.id] ?? []).some((n) => n.targetId === p.id && n.isMafia));
    if (found) return found;
    const cleared = new Set((g.notes[bot.id] ?? []).filter((n) => !n.isMafia).map((n) => n.targetId));
    const fresh = pool.filter((p) => !cleared.has(p.id));
    if (fresh.length) return pickOf(fresh, rng);
  }
  return pickOf(pool, rng);
}
function act(room, g, id, bot, rng) {
  const [kind] = id.split(":");
  const persona = bot.persona ?? "warm";
  const L = LINES[persona];
  const name = (p) => p?.name ?? "someone";
  const mem = room.bots;
  const bump = () => mem.done[id] = (mem.done[id] ?? 0) + 1;
  if (kind === "ack") {
    g.ackRole(bot.id);
  } else if (kind === "night") {
    const allowed = new Set(g.canTarget(bot.id));
    let pool = g.alive().filter((p) => allowed.has(p.id));
    if (bot.role === "mafia") {
      const partner = Object.entries(g.mafiaPicks).find(([mid]) => mid !== bot.id);
      const target = partner ? g.player(partner[1]) : chooseTarget(g, bot, pool, rng);
      if (target) g.nightAction(bot.id, target.id);
    } else if (bot.role === "doctor") {
      g.nightAction(bot.id, pickOf(pool, rng).id);
    } else {
      const t = chooseTarget(g, bot, pool, rng);
      if (t) g.nightAction(bot.id, t.id);
    }
  } else if (kind === "vote") {
    const pool = g.phase === "vote" && g.voteStage === "final" && g.defendants.length ? g.alive().filter((p) => g.defendants.includes(p.id) && p.id !== bot.id) : suspects(g, bot);
    const final = g.voteStage === "final" && g.defendants.length > 0;
    let target = "skip";
    const mafiaAllies = new Set(g.alive("mafia").map((p) => p.id));
    if (!final) {
      const choices = bot.role === "mafia" ? pool.filter((p) => !mafiaAllies.has(p.id)) : pool;
      const counts = g.tally();
      const leaning = choices.filter((p) => (counts[p.id] ?? 0) > 0).sort((a, b) => (counts[b.id] ?? 0) - (counts[a.id] ?? 0))[0];
      const pickChoice = bot.role === "mafia" && leaning && rng() < 0.6 ? leaning : chooseTarget(g, bot, choices, rng);
      if (pickChoice && rng() > 0.08) target = pickChoice.id;
    } else if (pool.length) {
      const d = pool[0];
      const known = (g.notes[bot.id] ?? []).find((n) => n.targetId === d.id);
      let eliminate;
      if (bot.role === "mafia") eliminate = !mafiaAllies.has(d.id);
      else if (known) eliminate = known.isMafia;
      else eliminate = rng() < 0.6;
      if (eliminate) target = d.id;
    }
    g.castVote(bot.id, target);
  } else if (kind === "talk") {
    const n = mem.done[id] ?? 0;
    const others = suspects(g, bot);
    const death = g.lastNightDeathId ? g.player(g.lastNightDeathId) : void 0;
    let text;
    if (n === 0 && death && rng() < 0.7) {
      text = fill(pickOf(L.death, rng), { v: name(death) });
    } else if (rng() < 0.25 && n === 1) {
      text = pickOf(L.claim, rng);
    } else {
      let pool = others;
      if (bot.role === "mafia") pool = others.filter((p) => !g.alive("mafia").some((m) => m.id === p.id));
      const t = bot.role === "detective" ? chooseTarget(g, bot, pool, rng) : pickOf(pool.length ? pool : others, rng);
      text = t ? fill(pickOf(L.accuse, rng), { t: name(t) }) : pickOf(L.claim, rng);
    }
    g.say(bot.id, text);
    bump();
  } else if (kind === "defend") {
    g.say(bot.id, pickOf(L.defend, rng));
    bump();
  } else if (kind === "reply") {
    g.say(bot.id, fill(pickOf(L.reply, rng), { n: "friend" }));
    mem.replies = mem.replies.filter((r) => r !== bot.id);
  }
}
function runBots(room, g, now, t, rng = Math.random) {
  if (!g.players.some((p) => p.bot)) {
    room.botNext = null;
    return false;
  }
  syncBots(room, g);
  let changed = false;
  for (let pass = 0; pass < 6; pass++) {
    const pending = tasks(room, g, t);
    let acted = false;
    for (const task of pending) {
      const mem = room.bots;
      if (mem.due[task.id] === void 0) mem.due[task.id] = now + task.min + rng() * Math.max(0, task.max - task.min);
      if (now >= mem.due[task.id]) {
        delete mem.due[task.id];
        act(room, g, task.id, task.bot, rng);
        changed = acted = true;
      }
    }
    if (!acted) break;
  }
  const waiting = tasks(room, g, t).map((x) => room.bots.due[x.id]).filter((d) => d !== void 0);
  room.botNext = waiting.length ? Math.min(...waiting) : null;
  void shuffle;
  return changed;
}

// shared/room.ts
var DEFAULT_TIMING = {
  revealMs: 2500,
  revealMaxMs: 9e4,
  nightPaceMs: 5e3,
  nightSilentMinMs: 5e3,
  nightSilentMaxMs: 9e3,
  nightStepMaxMs: 45e3,
  dawnMs: 15e3,
  resultMs: 12e3,
  voteAllInMs: 2500,
  defenseLeadMs: 6e3,
  botRevealMinMs: 800,
  botRevealMaxMs: 4e3,
  botNightMinMs: 1500,
  botNightMaxMs: 6e3,
  botVoteMinMs: 4e3,
  botVoteMaxMs: 4e4,
  botTalkMinMs: 5e3,
  botTalkMaxMs: 11e4,
  botDefendMinMs: 4e3,
  botDefendMaxMs: 9e3,
  botReplyMinMs: 2500,
  botReplyMaxMs: 7e3
};
var INSTANT_TIMING = Object.fromEntries(
  Object.keys(DEFAULT_TIMING).map((k) => [k, 0])
);
var HEARTBEAT_MS = 2e4;
var CONNECTED_WINDOW_MS = 5e4;
function newRoom(code, now) {
  return { code, game: new Game().toJSON(), key: "lobby", due: null, seen: {}, updatedAt: now };
}
function load(room) {
  return Game.fromJSON(room.game);
}
function save(room, game, now) {
  room.game = game.toJSON();
  room.updatedAt = now;
}
function keyOf2(g) {
  switch (g.phase) {
    case "reveal":
      return `reveal:${g.revealComplete() ? 1 : 0}`;
    case "night":
      return `night:${g.round}:${g.stepIdx}:${g.stepComplete() ? 1 : 0}`;
    default:
      return `${g.skipToken()}:${g.phase === "vote" && g.voteComplete() ? 1 : 0}`;
  }
}
function delayFor(g, t, rng) {
  switch (g.phase) {
    case "reveal":
      return g.revealComplete() ? t.revealMs : t.revealMaxMs;
    case "night":
      if (g.stepComplete()) {
        return g.stepIsEmpty() ? t.nightSilentMinMs + rng() * (t.nightSilentMaxMs - t.nightSilentMinMs) : t.nightPaceMs;
      }
      return t.nightStepMaxMs;
    case "dawn":
      return t.dawnMs;
    case "day":
      return g.settings.dayTimerSec * 1e3;
    case "vote":
      return g.voteComplete() ? t.voteAllInMs : g.settings.voteTimerSec * 1e3;
    case "defense":
      return g.settings.defenseSec * 1e3 + t.defenseLeadMs;
    case "result":
      return t.resultMs;
    default:
      return null;
  }
}
function schedule(room, g, now, t, rng = Math.random) {
  const key = keyOf2(g);
  if (key === room.key) return;
  room.key = key;
  const d = delayFor(g, t, rng);
  room.due = d === null ? null : now + d;
}
function fire(g) {
  switch (g.phase) {
    case "reveal":
      g.players.forEach((p) => p.seenRole = true);
      g.beginNight();
      break;
    case "night":
      g.advanceNight(true);
      break;
    case "dawn":
      g.startDay();
      break;
    case "day":
      g.startVote();
      break;
    case "vote":
      g.resolveVote();
      break;
    case "defense":
      g.advanceDefense();
      break;
    case "result":
      g.beginNight();
      break;
  }
}
function tick(room, now, t = DEFAULT_TIMING, rng = Math.random) {
  const g = load(room);
  let changed = false;
  if (runBots(room, g, now, t, rng)) {
    changed = true;
    schedule(room, g, now, t, rng);
  }
  for (let i = 0; i < 12 && room.due !== null && now >= room.due; i++) {
    const before = g.phase;
    fire(g);
    changed = true;
    room.key = "";
    schedule(room, g, Math.max(now, room.due ?? now), t, rng);
    if (g.phase === before && room.due !== null && room.due <= now) room.due = now + 1;
    if (runBots(room, g, now, t, rng)) schedule(room, g, now, t, rng);
  }
  if (changed) save(room, g, now);
  return changed;
}
var ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ";
function randomCode(rng = Math.random) {
  return Array.from({ length: 4 }, () => ALPHABET[Math.floor(rng() * ALPHABET.length)]).join("");
}
function buildView(room, token, now) {
  const g = load(room);
  for (const p of g.players) p.connected = !!p.bot || now - (room.seen[p.id] ?? 0) < CONNECTED_WINDOW_MS;
  const view = g.viewFor(token ?? null);
  return { ...view, code: room.code, now, due: room.due };
}
function applyAction(room, a, now, t, rng = Math.random) {
  const g = load(room);
  let r = { ok: true };
  const token = "token" in a && a.token || "";
  switch (a.action) {
    case "join":
      r = g.settings.visibility === "ask" && g.players.length > 0 && !g.player(a.token) ? g.requestJoin(a.token, a.name) : g.addPlayer(a.token, a.name);
      break;
    case "admit":
      r = hostOnly(g, token) ?? g.admit(a.target);
      break;
    case "decline":
      r = hostOnly(g, token) ?? g.decline(a.target);
      break;
    case "kick":
      r = hostOnly(g, token) ?? g.kick(a.target);
      break;
    case "settings":
      r = hostOnly(g, token) ?? g.updateSettings(a.patch);
      break;
    case "start":
      r = hostOnly(g, token) ?? g.start();
      break;
    case "ack":
      r = g.ackRole(token);
      break;
    case "night":
      r = g.nightAction(token, a.target);
      break;
    case "vote":
      r = g.castVote(token, a.target);
      break;
    case "skip":
      r = hostOnly(g, token) ?? skipPhase(room, g, a.at);
      break;
    case "rematch":
      r = hostOnly(g, token) ?? g.rematch();
      break;
    case "leave":
      r = g.removePlayer(token);
      break;
    case "addBot": {
      r = hostOnly(g, token) ?? { ok: true };
      for (let i = 0; r.ok && i < Math.min(Math.max(a.count ?? 1, 1), 10); i++) r = g.addBot();
      break;
    }
    case "removeBot":
      r = hostOnly(g, token) ?? (g.player(a.target)?.bot ? g.removePlayer(a.target) : { ok: false, error: "That is not a bot." });
      break;
    case "say":
      r = g.say(token, a.text);
      if (r.ok) {
        save(room, g, now);
        noteMentions(room, g, token, a.text);
      }
      break;
    default:
      return { ok: false, error: "Unknown action." };
  }
  if (!r.ok) return r;
  if (a.action === "rematch" || a.action === "start") room.key = "";
  save(room, g, now);
  schedule(room, g, now, t, rng);
  return r;
}
function hostOnly(g, id) {
  return g.hostId === id ? null : { ok: false, error: "Only the host can do that." };
}
function skipPhase(room, g, at) {
  if (g.skipToken() === at && room.due !== null) room.due = 0;
  return { ok: true };
}
function heartbeat(room, id, now) {
  if (!id || !room.seen || now - (room.seen[id] ?? 0) < HEARTBEAT_MS) return false;
  room.seen[id] = now;
  return true;
}
function isListed(g) {
  return g.phase === "lobby" && g.settings.visibility !== "private" && g.players.some((p) => !p.bot);
}
function summarize(room) {
  const g = load(room);
  if (!isListed(g)) return null;
  const host = g.player(g.hostId)?.name ?? "Host";
  return {
    code: room.code,
    name: g.settings.roomName || `${host}'s game`,
    host,
    players: g.players.length,
    max: 20,
    mode: g.settings.mode,
    visibility: g.settings.visibility
  };
}

// shared/handler.ts
var err = (error, status = 400) => ({ ok: false, error, status });
async function syncIndex(store, room) {
  const listed = isListed(load(room));
  if ((room.listed ?? false) !== listed) {
    room.listed = listed;
    await store.index(room.code, listed);
  }
}
async function handleRooms(store) {
  const codes = (await store.openCodes()).slice(0, 60);
  const docs = await store.getMany(codes);
  const rooms = [];
  await Promise.all(
    docs.map(async (doc, i) => {
      const s = doc ? summarize(doc) : null;
      if (s) rooms.push(s);
      else await store.index(codes[i], false);
    })
  );
  rooms.sort((a, b) => b.players - a.players || a.name.localeCompare(b.name));
  return { ok: true, rooms: rooms.slice(0, 25) };
}
async function handle(a, store, now = Date.now(), timing = DEFAULT_TIMING, rng = Math.random) {
  if (!a || typeof a !== "object" || typeof a.action !== "string") return err("Bad request.");
  if (a.action === "create") {
    if (!a.token || !a.name) return err("Enter your name.");
    for (let i = 0; i < 20; i++) {
      const code2 = randomCode(rng);
      const release2 = await store.lock(code2);
      try {
        if (await store.get(code2)) continue;
        const room = newRoom(code2, now);
        const r = applyAction(room, { action: "join", code: code2, token: a.token, name: a.name }, now, timing, rng);
        if (!r.ok) return err(r.error);
        room.seen[a.token] = now;
        const g0 = load(room);
        g0.updateSettings({ roomName: `${g0.players[0].name}'s game` });
        room.game = g0.toJSON();
        await store.set(code2, room);
        return { ok: true, code: code2, view: buildView(room, a.token, now) };
      } finally {
        await release2();
      }
    }
    return err("Could not create a room. Try again.", 503);
  }
  const code = String(a.code ?? "").toUpperCase().trim();
  if (!/^[A-Z]{4}$/.test(code)) return err("Enter the 4-letter room code.");
  const token = a.token;
  if (a.action === "poll" || a.action === "watch") {
    const peek = await store.get(code);
    if (!peek) return err("Room not found.", 404);
    const needsWrite = peek.due !== null && now >= peek.due || peek.botNext != null && now >= peek.botNext || token && now - (peek.seen[token] ?? 0) >= HEARTBEAT_MS;
    if (!needsWrite) return { ok: true, code, view: buildView(peek, token, now) };
  }
  const release = await store.lock(code);
  try {
    const room = await store.get(code);
    if (!room) return err("Room not found.", 404);
    tick(room, now, timing, rng);
    let result = { ok: true };
    if (a.action !== "poll" && a.action !== "watch") {
      result = applyAction(room, a, now, timing, rng);
      if (result.ok) tick(room, now, timing, rng);
    }
    if (result.ok) {
      heartbeat(room, token, now);
      if (a.action === "join" && token) room.seen[token] = now;
      await syncIndex(store, room);
      await store.set(code, room);
      return { ok: true, code, view: buildView(room, token, now) };
    }
    await store.set(code, room);
    return err(result.error);
  } finally {
    await release();
  }
}

// shared/store.ts
var TTL_SEC = 60 * 60 * 8;
var MemoryStore = class {
  rooms = /* @__PURE__ */ new Map();
  listed = /* @__PURE__ */ new Set();
  feedback = [];
  hits = /* @__PURE__ */ new Map();
  chains = /* @__PURE__ */ new Map();
  async get(code) {
    const raw = this.rooms.get(code);
    return raw ? JSON.parse(raw) : null;
  }
  async set(code, room) {
    this.rooms.set(code, JSON.stringify(room));
  }
  async pushFeedback(item) {
    this.feedback.push(item);
  }
  async listFeedback(limit) {
    return this.feedback.slice(-limit);
  }
  async hit(key, windowSec) {
    const now = Date.now();
    const cur = this.hits.get(key);
    const rec = cur && cur.until > now ? cur : { n: 0, until: now + windowSec * 1e3 };
    rec.n += 1;
    this.hits.set(key, rec);
    return rec.n;
  }
  async index(code, listed) {
    if (listed) this.listed.add(code);
    else this.listed.delete(code);
  }
  async openCodes() {
    return [...this.listed];
  }
  async getMany(codes) {
    return Promise.all(codes.map((c) => this.get(c)));
  }
  async lock(code) {
    const prev = this.chains.get(code) ?? Promise.resolve();
    let release;
    const next = new Promise((res) => release = res);
    this.chains.set(code, prev.then(() => next));
    await prev;
    return async () => release();
  }
};
var RedisStore = class {
  constructor(url, token) {
    this.url = url;
    this.token = token;
  }
  url;
  token;
  async cmd(...args) {
    const res = await fetch(this.url, {
      method: "POST",
      headers: { Authorization: `Bearer ${this.token}`, "Content-Type": "application/json" },
      body: JSON.stringify(args)
    });
    if (!res.ok) throw new Error(`Redis ${res.status}`);
    return (await res.json()).result;
  }
  async get(code) {
    const raw = await this.cmd("GET", `mgm:room:${code}`);
    return raw ? JSON.parse(raw) : null;
  }
  async set(code, room) {
    await this.cmd("SET", `mgm:room:${code}`, JSON.stringify(room), "EX", TTL_SEC);
  }
  async pushFeedback(item) {
    await this.cmd("RPUSH", "mgm:feedback", JSON.stringify(item));
    await this.cmd("LTRIM", "mgm:feedback", -2e4, -1);
  }
  async listFeedback(limit) {
    const raws = await this.cmd("LRANGE", "mgm:feedback", -limit, -1) ?? [];
    return raws.map((r) => JSON.parse(r));
  }
  async hit(key, windowSec) {
    const n = await this.cmd("INCR", `mgm:hit:${key}`);
    if (n === 1) await this.cmd("EXPIRE", `mgm:hit:${key}`, windowSec);
    return n;
  }
  async index(code, listed) {
    await this.cmd(listed ? "SADD" : "SREM", "mgm:open", code);
  }
  async openCodes() {
    return await this.cmd("SMEMBERS", "mgm:open") ?? [];
  }
  async getMany(codes) {
    if (!codes.length) return [];
    const raws = await this.cmd("MGET", ...codes.map((c) => `mgm:room:${c}`));
    return raws.map((r) => r ? JSON.parse(r) : null);
  }
  async lock(code) {
    const key = `mgm:lock:${code}`;
    const id = Math.random().toString(36).slice(2);
    for (let i = 0; i < 40; i++) {
      const got = await this.cmd("SET", key, id, "NX", "PX", 4e3);
      if (got === "OK") {
        return async () => {
          const cur = await this.cmd("GET", key);
          if (cur === id) await this.cmd("DEL", key);
        };
      }
      await new Promise((r) => setTimeout(r, 60));
    }
    throw new Error("Room is busy, try again.");
  }
};
var shared = null;
function defaultStore() {
  if (shared) return shared;
  const url = process.env.UPSTASH_REDIS_REST_URL ?? process.env.KV_REST_API_URL;
  const token = process.env.UPSTASH_REDIS_REST_TOKEN ?? process.env.KV_REST_API_TOKEN;
  shared = url && token ? new RedisStore(url, token) : new MemoryStore();
  return shared;
}

// functions/room.ts
async function handler(req, res) {
  res.setHeader("Cache-Control", "no-store");
  if (req.method !== "POST") return res.status(405).json({ ok: false, error: "Use POST." });
  try {
    if (req.body?.action === "rooms") return res.status(200).json(await handleRooms(defaultStore()));
    const out = await handle(req.body, defaultStore());
    return res.status(out.ok ? 200 : out.status ?? 400).json(out);
  } catch (e) {
    return res.status(500).json({ ok: false, error: e instanceof Error ? e.message : "Server error." });
  }
}
module.exports = module.exports.default;
