// GENERATED by `npm run build:api` from functions/room.ts. Do not edit.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// functions/room.ts
var room_exports = {};
__export(room_exports, {
  default: () => handler
});
module.exports = __toCommonJS(room_exports);

// shared/game.ts
var DEFAULT_SETTINGS = {
  mode: "table",
  doctorSelfSave: true,
  doctorRepeatSave: true,
  useDoctor: true,
  useDetective: true,
  mafiaCount: null,
  revealRoleOnDeath: false,
  deadSeeRoles: false,
  dayTimerSec: 180,
  voteTimerSec: 60
};
var MIN_PLAYERS = 4;
var MAX_PLAYERS = 20;
var ok = (value) => ({ ok: true, value });
var fail = (error) => ({ ok: false, error });
function roleCounts(n, s) {
  const maxMafia = Math.max(1, Math.ceil(n / 2) - 1);
  const auto = Math.max(1, Math.floor(n / 3));
  const mafia = Math.min(maxMafia, Math.max(1, s.mafiaCount ?? auto));
  const doctor = s.useDoctor && n - mafia >= 2 ? 1 : 0;
  const detective = s.useDetective && n - mafia - doctor >= 1 ? 1 : 0;
  const villager = n - mafia - doctor - detective;
  return { mafia, doctor, detective, villager };
}
function shuffle(items, rng) {
  const a = [...items];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
var Game = class _Game {
  constructor(rng = Math.random) {
    this.rng = rng;
  }
  rng;
  phase = "lobby";
  round = 0;
  settings = { ...DEFAULT_SETTINGS };
  players = [];
  hostId = null;
  winner = null;
  lines = [];
  notes = {};
  // night
  steps = [];
  stepIdx = 0;
  mafiaPicks = {};
  doctorPick = null;
  detectivePick = null;
  lastSaved = null;
  // day
  votes = {};
  // voterId -> targetId | "skip"
  lastResult = null;
  lastNightDeathId = null;
  seq = 0;
  static fromJSON(data, rng = Math.random) {
    return Object.assign(new _Game(rng), structuredClone(data));
  }
  toJSON() {
    const { rng: _rng, ...state } = this;
    return state;
  }
  // ---------- helpers ----------
  player(id) {
    return this.players.find((p) => p.id === id);
  }
  alive(role) {
    return this.players.filter((p) => p.alive && (!role || p.role === role));
  }
  narrate(text) {
    this.lines.push({ seq: ++this.seq, text });
    if (this.lines.length > 40) this.lines.shift();
  }
  classic() {
    return this.settings.mode !== "remote";
  }
  get step() {
    return this.phase === "night" ? this.steps[this.stepIdx] ?? null : null;
  }
  // ---------- lobby ----------
  addPlayer(id, name) {
    const existing = this.player(id);
    if (existing) {
      existing.connected = true;
      return ok();
    }
    if (this.phase !== "lobby") return fail("The game has already started.");
    const clean = name.trim().slice(0, 16);
    if (!clean) return fail("Enter a name.");
    if (this.players.length >= MAX_PLAYERS) return fail("The room is full.");
    if (this.players.some((p) => p.name.toLowerCase() === clean.toLowerCase())) return fail("That name is taken.");
    this.players.push({ id, name: clean, role: null, alive: true, connected: true, seenRole: false });
    this.hostId ??= id;
    return ok();
  }
  removePlayer(id) {
    if (this.phase !== "lobby") return fail("Players can only leave from the lobby.");
    this.players = this.players.filter((p) => p.id !== id);
    if (this.hostId === id) this.hostId = this.players.find((p) => p.connected)?.id ?? this.players[0]?.id ?? null;
    return ok();
  }
  setConnected(id, connected) {
    const p = this.player(id);
    if (p) p.connected = connected;
    if (!connected && this.hostId === id) {
      const next = this.players.find((q) => q.connected && q.id !== id);
      if (next) this.hostId = next.id;
    }
  }
  updateSettings(patch) {
    if (this.phase !== "lobby") return fail("Settings are locked once the game starts.");
    const s = { ...this.settings, ...patch };
    if (!["table", "phones", "remote"].includes(s.mode)) return fail("Unknown mode.");
    s.dayTimerSec = clamp(Math.round(Number(s.dayTimerSec)), 30, 900);
    s.voteTimerSec = clamp(Math.round(Number(s.voteTimerSec)), 15, 300);
    s.mafiaCount = s.mafiaCount == null ? null : clamp(Math.round(Number(s.mafiaCount)), 1, 9);
    for (const k of ["doctorSelfSave", "doctorRepeatSave", "useDoctor", "useDetective", "revealRoleOnDeath", "deadSeeRoles"]) {
      s[k] = Boolean(s[k]);
    }
    this.settings = s;
    return ok();
  }
  start() {
    if (this.phase !== "lobby") return fail("The game has already started.");
    const n = this.players.length;
    if (n < MIN_PLAYERS) return fail(`You need at least ${MIN_PLAYERS} players.`);
    const c = roleCounts(n, this.settings);
    const deck = [
      ...Array(c.mafia).fill("mafia"),
      ...Array(c.doctor).fill("doctor"),
      ...Array(c.detective).fill("detective"),
      ...Array(c.villager).fill("villager")
    ];
    shuffle(deck, this.rng).forEach((role, i) => {
      const p = this.players[i];
      p.role = role;
      p.alive = true;
      p.seenRole = false;
    });
    this.notes = {};
    this.winner = null;
    this.round = 0;
    this.lastSaved = null;
    this.lines = [];
    this.phase = "reveal";
    this.narrate("Check your phone to see your secret role. Keep it to yourself.");
    return ok();
  }
  // ---------- role reveal ----------
  ackRole(id) {
    if (this.phase !== "reveal") return fail("Not time to confirm roles.");
    const p = this.player(id);
    if (!p) return fail("Unknown player.");
    p.seenRole = true;
    return ok();
  }
  revealComplete() {
    return this.phase === "reveal" && this.players.every((p) => p.seenRole || !p.connected);
  }
  // ---------- night ----------
  beginNight() {
    this.round += 1;
    this.phase = "night";
    this.steps = ["mafia"];
    if (this.players.some((p) => p.role === "doctor")) this.steps.push("doctor");
    if (this.players.some((p) => p.role === "detective")) this.steps.push("detective");
    this.stepIdx = 0;
    this.mafiaPicks = {};
    this.doctorPick = null;
    this.detectivePick = null;
    this.votes = {};
    this.lastResult = null;
    this.narrate(
      this.classic() ? "Night falls. Everyone, close your eyes." : "Night falls. Night roles, check your phones."
    );
    this.announceStep(null);
  }
  announceStep(prev) {
    const step = this.steps[this.stepIdx];
    const label = { mafia: "Mafia", doctor: "Doctor", detective: "Detective" };
    const prompt = {
      mafia: "Agree on who to eliminate.",
      doctor: "Choose someone to save.",
      detective: "Choose someone to investigate."
    };
    const parts = [];
    if (this.classic()) {
      if (prev) parts.push(`${label[prev]}, close your eyes.`);
      parts.push(`${label[step]}, open your eyes. ${prompt[step]}`);
    } else {
      parts.push(`${label[step]}: ${prompt[step]}`);
    }
    this.narrate(parts.join(" "));
  }
  /** Players who must act in the current night step. */
  actors() {
    const step = this.step;
    return step ? this.alive(step) : [];
  }
  canTarget(playerId) {
    const step = this.step;
    const me = this.player(playerId);
    if (!step || !me || !me.alive || me.role !== step) return [];
    let pool = this.alive();
    if (step === "mafia") pool = pool.filter((p) => p.role !== "mafia");
    if (step === "detective") pool = pool.filter((p) => p.id !== me.id);
    if (step === "doctor") {
      if (!this.settings.doctorSelfSave) pool = pool.filter((p) => p.id !== me.id);
      if (!this.settings.doctorRepeatSave && this.lastSaved) pool = pool.filter((p) => p.id !== this.lastSaved);
    }
    return pool.map((p) => p.id);
  }
  nightAction(playerId, targetId) {
    const step = this.step;
    if (!step) return fail("It is not night.");
    const me = this.player(playerId);
    if (!me?.alive || me.role !== step) return fail("It is not your turn.");
    if (!this.canTarget(playerId).includes(targetId)) return fail("You cannot choose that player.");
    if (step === "mafia") this.mafiaPicks[playerId] = targetId;
    if (step === "doctor") this.doctorPick = targetId;
    if (step === "detective") {
      if (this.detectivePick) return fail("You already investigated tonight.");
      this.detectivePick = targetId;
      const target = this.player(targetId);
      (this.notes[playerId] ??= []).push({ night: this.round, targetId, isMafia: target.role === "mafia" });
    }
    return ok();
  }
  /** True when no one is left to act, so the server should skip the step quietly. */
  stepIsEmpty() {
    return this.step !== null && this.actors().length === 0;
  }
  stepComplete() {
    const step = this.step;
    if (!step) return false;
    if (this.stepIsEmpty()) return true;
    if (step === "mafia") {
      const mafia = this.actors();
      const picks = mafia.map((m) => this.mafiaPicks[m.id]);
      return picks.every(Boolean) && new Set(picks).size === 1;
    }
    if (step === "doctor") return this.doctorPick !== null;
    return this.detectivePick !== null;
  }
  /** Move to the next night step, or resolve the night. `force` settles missing picks. */
  advanceNight(force = false) {
    const step = this.step;
    if (!step) return;
    if (!force && !this.stepComplete()) return;
    this.stepIdx += 1;
    if (this.stepIdx < this.steps.length) {
      this.announceStep(step);
    } else {
      if (this.classic()) this.narrate(`${{ mafia: "Mafia", doctor: "Doctor", detective: "Detective" }[step]}, close your eyes.`);
      this.resolveNight();
    }
  }
  mafiaTarget() {
    const tally = /* @__PURE__ */ new Map();
    for (const m of this.alive("mafia")) {
      const t = this.mafiaPicks[m.id];
      if (t) tally.set(t, (tally.get(t) ?? 0) + 1);
    }
    if (!tally.size) return null;
    const top = Math.max(...tally.values());
    const tied = [...tally].filter(([, n]) => n === top).map(([id]) => id).sort();
    return tied[Math.floor(this.rng() * tied.length)];
  }
  resolveNight() {
    const target = this.mafiaTarget();
    const saved = target !== null && target === this.doctorPick;
    this.lastSaved = this.doctorPick;
    const victim = target && !saved ? this.player(target) : null;
    if (victim) victim.alive = false;
    this.lastNightDeathId = victim?.id ?? null;
    this.phase = "dawn";
    const open = this.classic() ? "Everyone, open your eyes. Morning has come. " : "Morning has come. ";
    const role = victim && this.settings.revealRoleOnDeath ? ` They were ${article(victim.role)}.` : "";
    this.narrate(open + (victim ? `${victim.name} was killed in the night.${role}` : "Nobody died last night."));
    this.checkWin();
  }
  // ---------- day ----------
  startDay() {
    if (this.phase !== "dawn") return;
    this.phase = "day";
    this.narrate("Discuss who you think is Mafia. Voting opens when the timer ends.");
  }
  startVote() {
    if (this.phase !== "day") return;
    this.phase = "vote";
    this.votes = {};
    this.narrate("Time to vote. Pick a player, or skip.");
  }
  castVote(playerId, targetId) {
    if (this.phase !== "vote") return fail("Voting is not open.");
    const me = this.player(playerId);
    if (!me?.alive) return fail("Only living players can vote.");
    if (targetId !== "skip") {
      const t = this.player(targetId);
      if (!t?.alive) return fail("Pick a living player.");
      if (t.id === me.id) return fail("You cannot vote for yourself.");
    }
    this.votes[playerId] = targetId;
    return ok();
  }
  voteComplete() {
    return this.phase === "vote" && this.alive().every((p) => this.votes[p.id]);
  }
  tally() {
    const counts = {};
    for (const t of Object.values(this.votes)) counts[t] = (counts[t] ?? 0) + 1;
    return counts;
  }
  resolveVote() {
    if (this.phase !== "vote") return;
    const counts = this.tally();
    const entries = Object.entries(counts);
    const top = entries.length ? Math.max(...entries.map(([, n]) => n)) : 0;
    const leaders = entries.filter(([, n]) => n === top).map(([id]) => id);
    let eliminated = null;
    let text;
    if (leaders.length !== 1 || leaders[0] === "skip") {
      text = leaders.length > 1 ? "The vote is tied. Nobody is eliminated." : "Nobody is eliminated.";
    } else {
      eliminated = this.player(leaders[0]);
      eliminated.alive = false;
      const role = this.settings.revealRoleOnDeath ? ` They were ${article(eliminated.role)}.` : "";
      text = `${eliminated.name} was eliminated with ${top} vote${top === 1 ? "" : "s"}.${role}`;
    }
    this.lastResult = { text, eliminatedId: eliminated?.id ?? null };
    this.phase = "result";
    this.narrate(text);
    this.checkWin();
  }
  // ---------- end ----------
  checkWin() {
    const mafia = this.alive("mafia").length;
    const town = this.alive().length - mafia;
    if (mafia === 0) this.finish("town", "The Town wins! Every Mafia member has been caught.");
    else if (mafia >= town) this.finish("mafia", "The Mafia wins! They now outnumber the town.");
  }
  finish(w, text) {
    this.winner = w;
    this.phase = "over";
    this.narrate(text);
  }
  rematch() {
    if (this.phase !== "over") return fail("The game is not over.");
    this.phase = "lobby";
    this.round = 0;
    this.winner = null;
    this.notes = {};
    this.lines = [];
    this.lastResult = null;
    for (const p of this.players) {
      p.role = null;
      p.alive = true;
      p.seenRole = false;
    }
    this.players = this.players.filter((p) => p.connected);
    return ok();
  }
  // ---------- views ----------
  /** What a given player (or the shared table screen, when null) may know. */
  viewFor(playerId) {
    const me = this.player(playerId);
    const over = this.phase === "over";
    const seeAll = over || me && !me.alive && this.settings.deadSeeRoles;
    const showRole = (p) => seeAll || p.id === me?.id || me?.role === "mafia" && p.role === "mafia" || !p.alive && this.settings.revealRoleOnDeath;
    const counts = this.phase === "vote" || this.phase === "result" ? this.tally() : {};
    const step = this.step;
    return {
      phase: this.phase,
      round: this.round,
      settings: this.settings,
      hostId: this.hostId,
      winner: this.winner,
      lines: this.lines.slice(-12),
      players: this.players.map((p) => ({
        id: p.id,
        name: p.name,
        alive: p.alive,
        connected: p.connected,
        seenRole: p.seenRole,
        role: this.phase === "lobby" ? null : showRole(p) ? p.role : null
      })),
      you: me ? {
        id: me.id,
        name: me.name,
        role: me.role,
        alive: me.alive,
        isHost: me.id === this.hostId,
        notes: this.notes[me.id] ?? []
      } : null,
      night: {
        step: this.phase === "night" ? step : null,
        yourTargets: me ? this.canTarget(me.id) : [],
        yourPick: me?.role === "mafia" ? this.mafiaPicks[me.id] ?? null : me?.role === "doctor" ? this.doctorPick : me?.role === "detective" ? this.detectivePick : null,
        mafiaPicks: me?.role === "mafia" && this.step === "mafia" ? this.mafiaPicks : {}
      },
      vote: {
        counts,
        yourVote: me ? this.votes[me.id] ?? null : null,
        voted: this.phase === "vote" ? Object.keys(this.votes).length : 0,
        eligible: this.alive().length
      },
      result: this.lastResult,
      minPlayers: MIN_PLAYERS,
      suggested: roleCounts(Math.max(this.players.length, MIN_PLAYERS), this.settings)
    };
  }
};
function clamp(n, lo, hi) {
  return Number.isFinite(n) ? Math.min(hi, Math.max(lo, n)) : lo;
}
function article(role) {
  return role === "mafia" ? "a Mafia member" : role === "villager" ? "a Villager" : `the ${role[0].toUpperCase()}${role.slice(1)}`;
}

// shared/room.ts
var DEFAULT_TIMING = {
  revealMs: 2500,
  revealMaxMs: 9e4,
  nightPaceMs: 3500,
  nightSilentMinMs: 5e3,
  nightSilentMaxMs: 9e3,
  nightStepMaxMs: 45e3,
  dawnMs: 9e3,
  resultMs: 9e3,
  voteAllInMs: 2500
};
var INSTANT_TIMING = Object.fromEntries(
  Object.keys(DEFAULT_TIMING).map((k) => [k, 0])
);
var HEARTBEAT_MS = 2e4;
var CONNECTED_WINDOW_MS = 5e4;
function newRoom(code, now) {
  return { code, game: new Game().toJSON(), key: "lobby", due: null, seen: {}, updatedAt: now };
}
function load(room) {
  return Game.fromJSON(room.game);
}
function save(room, game, now) {
  room.game = game.toJSON();
  room.updatedAt = now;
}
function keyOf(g) {
  switch (g.phase) {
    case "reveal":
      return `reveal:${g.revealComplete() ? 1 : 0}`;
    case "night":
      return `night:${g.round}:${g.stepIdx}:${g.stepComplete() ? 1 : 0}`;
    default:
      return `${g.phase}:${g.round}:${g.phase === "vote" && g.voteComplete() ? 1 : 0}`;
  }
}
function delayFor(g, t, rng) {
  switch (g.phase) {
    case "reveal":
      return g.revealComplete() ? t.revealMs : t.revealMaxMs;
    case "night":
      if (g.stepComplete()) {
        return g.stepIsEmpty() ? t.nightSilentMinMs + rng() * (t.nightSilentMaxMs - t.nightSilentMinMs) : t.nightPaceMs;
      }
      return t.nightStepMaxMs;
    case "dawn":
      return t.dawnMs;
    case "day":
      return g.settings.dayTimerSec * 1e3;
    case "vote":
      return g.voteComplete() ? t.voteAllInMs : g.settings.voteTimerSec * 1e3;
    case "result":
      return t.resultMs;
    default:
      return null;
  }
}
function schedule(room, g, now, t, rng = Math.random) {
  const key = keyOf(g);
  if (key === room.key) return;
  room.key = key;
  const d = delayFor(g, t, rng);
  room.due = d === null ? null : now + d;
}
function fire(g) {
  switch (g.phase) {
    case "reveal":
      g.players.forEach((p) => p.seenRole = true);
      g.beginNight();
      break;
    case "night":
      g.advanceNight(true);
      break;
    case "dawn":
      g.startDay();
      break;
    case "day":
      g.startVote();
      break;
    case "vote":
      g.resolveVote();
      break;
    case "result":
      g.beginNight();
      break;
  }
}
function tick(room, now, t = DEFAULT_TIMING, rng = Math.random) {
  const g = load(room);
  let changed = false;
  for (let i = 0; i < 12 && room.due !== null && now >= room.due; i++) {
    const before = g.phase;
    fire(g);
    changed = true;
    room.key = "";
    schedule(room, g, Math.max(now, room.due ?? now), t, rng);
    if (g.phase === before && room.due !== null && room.due <= now) room.due = now + 1;
  }
  if (changed) save(room, g, now);
  return changed;
}
var ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ";
function randomCode(rng = Math.random) {
  return Array.from({ length: 4 }, () => ALPHABET[Math.floor(rng() * ALPHABET.length)]).join("");
}
function buildView(room, token, now) {
  const g = load(room);
  for (const p of g.players) p.connected = now - (room.seen[p.id] ?? 0) < CONNECTED_WINDOW_MS;
  const view = g.viewFor(token ?? null);
  return { ...view, code: room.code, now, due: room.due };
}
function applyAction(room, a, now, t, rng = Math.random) {
  const g = load(room);
  let r = { ok: true };
  const token = "token" in a && a.token || "";
  switch (a.action) {
    case "join":
      r = g.addPlayer(a.token, a.name);
      break;
    case "settings":
      r = hostOnly(g, token) ?? g.updateSettings(a.patch);
      break;
    case "start":
      r = hostOnly(g, token) ?? g.start();
      break;
    case "ack":
      r = g.ackRole(token);
      break;
    case "night":
      r = g.nightAction(token, a.target);
      break;
    case "vote":
      r = g.castVote(token, a.target);
      break;
    case "skip":
      r = hostOnly(g, token) ?? skipPhase(room, g, a.phase, a.round);
      break;
    case "rematch":
      r = hostOnly(g, token) ?? g.rematch();
      break;
    case "leave":
      r = g.removePlayer(token);
      break;
    default:
      return { ok: false, error: "Unknown action." };
  }
  if (!r.ok) return r;
  if (a.action === "rematch" || a.action === "start") room.key = "";
  save(room, g, now);
  schedule(room, g, now, t, rng);
  return r;
}
function hostOnly(g, id) {
  return g.hostId === id ? null : { ok: false, error: "Only the host can do that." };
}
function skipPhase(room, g, phase, round) {
  if (g.phase === phase && g.round === round && room.due !== null) room.due = 0;
  return { ok: true };
}
function heartbeat(room, id, now) {
  if (!id || !room.seen || now - (room.seen[id] ?? 0) < HEARTBEAT_MS) return false;
  room.seen[id] = now;
  return true;
}

// shared/handler.ts
var err = (error, status = 400) => ({ ok: false, error, status });
async function handle(a, store, now = Date.now(), timing = DEFAULT_TIMING, rng = Math.random) {
  if (!a || typeof a !== "object" || typeof a.action !== "string") return err("Bad request.");
  if (a.action === "create") {
    if (!a.token || !a.name) return err("Enter your name.");
    for (let i = 0; i < 20; i++) {
      const code2 = randomCode(rng);
      const release2 = await store.lock(code2);
      try {
        if (await store.get(code2)) continue;
        const room = newRoom(code2, now);
        const r = applyAction(room, { action: "join", code: code2, token: a.token, name: a.name }, now, timing, rng);
        if (!r.ok) return err(r.error);
        room.seen[a.token] = now;
        await store.set(code2, room);
        return { ok: true, code: code2, view: buildView(room, a.token, now) };
      } finally {
        await release2();
      }
    }
    return err("Could not create a room. Try again.", 503);
  }
  const code = String(a.code ?? "").toUpperCase().trim();
  if (!/^[A-Z]{4}$/.test(code)) return err("Enter the 4-letter room code.");
  const token = a.token;
  if (a.action === "poll" || a.action === "watch") {
    const peek = await store.get(code);
    if (!peek) return err("Room not found.", 404);
    const needsWrite = peek.due !== null && now >= peek.due || token && now - (peek.seen[token] ?? 0) >= HEARTBEAT_MS;
    if (!needsWrite) return { ok: true, code, view: buildView(peek, token, now) };
  }
  const release = await store.lock(code);
  try {
    const room = await store.get(code);
    if (!room) return err("Room not found.", 404);
    tick(room, now, timing, rng);
    let result = { ok: true };
    if (a.action !== "poll" && a.action !== "watch") {
      result = applyAction(room, a, now, timing, rng);
      if (result.ok && a.action === "skip") tick(room, now, timing, rng);
    }
    if (result.ok) {
      heartbeat(room, token, now);
      if (a.action === "join" && token) room.seen[token] = now;
      await store.set(code, room);
      return { ok: true, code, view: buildView(room, token, now) };
    }
    await store.set(code, room);
    return err(result.error);
  } finally {
    await release();
  }
}

// shared/store.ts
var TTL_SEC = 60 * 60 * 8;
var MemoryStore = class {
  rooms = /* @__PURE__ */ new Map();
  chains = /* @__PURE__ */ new Map();
  async get(code) {
    const raw = this.rooms.get(code);
    return raw ? JSON.parse(raw) : null;
  }
  async set(code, room) {
    this.rooms.set(code, JSON.stringify(room));
  }
  async lock(code) {
    const prev = this.chains.get(code) ?? Promise.resolve();
    let release;
    const next = new Promise((res) => release = res);
    this.chains.set(code, prev.then(() => next));
    await prev;
    return async () => release();
  }
};
var RedisStore = class {
  constructor(url, token) {
    this.url = url;
    this.token = token;
  }
  url;
  token;
  async cmd(...args) {
    const res = await fetch(this.url, {
      method: "POST",
      headers: { Authorization: `Bearer ${this.token}`, "Content-Type": "application/json" },
      body: JSON.stringify(args)
    });
    if (!res.ok) throw new Error(`Redis ${res.status}`);
    return (await res.json()).result;
  }
  async get(code) {
    const raw = await this.cmd("GET", `mgm:room:${code}`);
    return raw ? JSON.parse(raw) : null;
  }
  async set(code, room) {
    await this.cmd("SET", `mgm:room:${code}`, JSON.stringify(room), "EX", TTL_SEC);
  }
  async lock(code) {
    const key = `mgm:lock:${code}`;
    const id = Math.random().toString(36).slice(2);
    for (let i = 0; i < 40; i++) {
      const got = await this.cmd("SET", key, id, "NX", "PX", 4e3);
      if (got === "OK") {
        return async () => {
          const cur = await this.cmd("GET", key);
          if (cur === id) await this.cmd("DEL", key);
        };
      }
      await new Promise((r) => setTimeout(r, 60));
    }
    throw new Error("Room is busy, try again.");
  }
};
var shared = null;
function defaultStore() {
  if (shared) return shared;
  const url = process.env.UPSTASH_REDIS_REST_URL ?? process.env.KV_REST_API_URL;
  const token = process.env.UPSTASH_REDIS_REST_TOKEN ?? process.env.KV_REST_API_TOKEN;
  shared = url && token ? new RedisStore(url, token) : new MemoryStore();
  return shared;
}

// functions/room.ts
async function handler(req, res) {
  res.setHeader("Cache-Control", "no-store");
  if (req.method !== "POST") return res.status(405).json({ ok: false, error: "Use POST." });
  try {
    const out = await handle(req.body, defaultStore());
    return res.status(out.ok ? 200 : out.status ?? 400).json(out);
  } catch (e) {
    return res.status(500).json({ ok: false, error: e instanceof Error ? e.message : "Server error." });
  }
}
module.exports = module.exports.default;
