// GENERATED by `npm run build:api` from functions/room.ts. Do not edit.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// functions/stats.ts
var stats_exports = {};
__export(stats_exports, {
  default: () => handler
});
module.exports = __toCommonJS(stats_exports);

// shared/feedback.ts
var import_node_crypto = require("node:crypto");
var hash = (s) => (0, import_node_crypto.createHash)("sha256").update(s).digest("hex").slice(0, 10);
function isAdmin(authHeader, adminKey) {
  if (!adminKey || adminKey.length < 12) return false;
  const given = (authHeader ?? "").replace(/^Bearer\s+/i, "");
  const a = Buffer.from(hash(given));
  const b = Buffer.from(hash(adminKey));
  return a.length === b.length && (0, import_node_crypto.timingSafeEqual)(a, b);
}

// shared/stats.ts
var count = (xs) => xs.reduce((m, x) => (m[x] = (m[x] ?? 0) + 1, m), {});
var avg = (xs) => xs.length ? Math.round(xs.reduce((a, b) => a + b, 0) / xs.length * 10) / 10 : 0;
function aggregate(records, now = Date.now()) {
  const day = 24 * 3600 * 1e3;
  const perDay = [];
  for (let i = 13; i >= 0; i--) {
    const start = new Date(now - i * day);
    const label = start.toISOString().slice(0, 10);
    perDay.push({ day: label, games: records.filter((r) => new Date(r.at).toISOString().slice(0, 10) === label).length });
  }
  return {
    games: records.length,
    last7days: records.filter((r) => now - r.at < 7 * day).length,
    avgPlayers: avg(records.map((r) => r.players)),
    avgBots: avg(records.map((r) => r.bots)),
    avgRounds: avg(records.map((r) => r.rounds)),
    gamesWithBots: records.filter((r) => r.bots > 0).length,
    winners: count(records.map((r) => r.winner)),
    languages: count(records.map((r) => r.language)),
    modes: count(records.map((r) => r.mode)),
    voteStyles: count(records.map((r) => r.voteStyle)),
    optionalRoles: count(records.flatMap((r) => r.roles)),
    perDay
  };
}

// shared/store.ts
var TTL_SEC = 60 * 60 * 8;
var MemoryStore = class {
  rooms = /* @__PURE__ */ new Map();
  listed = /* @__PURE__ */ new Set();
  feedback = [];
  games = [];
  hits = /* @__PURE__ */ new Map();
  chains = /* @__PURE__ */ new Map();
  async get(code) {
    const raw = this.rooms.get(code);
    return raw ? JSON.parse(raw) : null;
  }
  async set(code, room) {
    this.rooms.set(code, JSON.stringify(room));
  }
  async pushFeedback(item) {
    this.feedback.push(item);
  }
  async pushGame(rec) {
    this.games.push(rec);
  }
  async listGames(limit) {
    return this.games.slice(-limit);
  }
  async listFeedback(limit) {
    return this.feedback.slice(-limit);
  }
  async hit(key, windowSec) {
    const now = Date.now();
    const cur = this.hits.get(key);
    const rec = cur && cur.until > now ? cur : { n: 0, until: now + windowSec * 1e3 };
    rec.n += 1;
    this.hits.set(key, rec);
    return rec.n;
  }
  async index(code, listed) {
    if (listed) this.listed.add(code);
    else this.listed.delete(code);
  }
  async openCodes() {
    return [...this.listed];
  }
  async getMany(codes) {
    return Promise.all(codes.map((c) => this.get(c)));
  }
  async lock(code) {
    const prev = this.chains.get(code) ?? Promise.resolve();
    let release;
    const next = new Promise((res) => release = res);
    this.chains.set(code, prev.then(() => next));
    await prev;
    return async () => release();
  }
};
var RedisStore = class {
  constructor(url, token) {
    this.url = url;
    this.token = token;
  }
  url;
  token;
  async cmd(...args) {
    const res = await fetch(this.url, {
      method: "POST",
      headers: { Authorization: `Bearer ${this.token}`, "Content-Type": "application/json" },
      body: JSON.stringify(args)
    });
    if (!res.ok) throw new Error(`Redis ${res.status}`);
    return (await res.json()).result;
  }
  async get(code) {
    const raw = await this.cmd("GET", `mgm:room:${code}`);
    return raw ? JSON.parse(raw) : null;
  }
  async set(code, room) {
    await this.cmd("SET", `mgm:room:${code}`, JSON.stringify(room), "EX", TTL_SEC);
  }
  async pushGame(rec) {
    await this.cmd("RPUSH", "mgm:games", JSON.stringify(rec));
    await this.cmd("LTRIM", "mgm:games", -5e3, -1);
  }
  async listGames(limit) {
    const raws = await this.cmd("LRANGE", "mgm:games", -limit, -1) ?? [];
    return raws.map((r) => JSON.parse(r));
  }
  async pushFeedback(item) {
    await this.cmd("RPUSH", "mgm:feedback", JSON.stringify(item));
    await this.cmd("LTRIM", "mgm:feedback", -2e4, -1);
  }
  async listFeedback(limit) {
    const raws = await this.cmd("LRANGE", "mgm:feedback", -limit, -1) ?? [];
    return raws.map((r) => JSON.parse(r));
  }
  async hit(key, windowSec) {
    const n = await this.cmd("INCR", `mgm:hit:${key}`);
    if (n === 1) await this.cmd("EXPIRE", `mgm:hit:${key}`, windowSec);
    return n;
  }
  async index(code, listed) {
    await this.cmd(listed ? "SADD" : "SREM", "mgm:open", code);
  }
  async openCodes() {
    return await this.cmd("SMEMBERS", "mgm:open") ?? [];
  }
  async getMany(codes) {
    if (!codes.length) return [];
    const raws = await this.cmd("MGET", ...codes.map((c) => `mgm:room:${c}`));
    return raws.map((r) => r ? JSON.parse(r) : null);
  }
  async lock(code) {
    const key = `mgm:lock:${code}`;
    const id = Math.random().toString(36).slice(2);
    for (let i = 0; i < 40; i++) {
      const got = await this.cmd("SET", key, id, "NX", "PX", 4e3);
      if (got === "OK") {
        return async () => {
          const cur = await this.cmd("GET", key);
          if (cur === id) await this.cmd("DEL", key);
        };
      }
      await new Promise((r) => setTimeout(r, 60));
    }
    throw new Error("Room is busy, try again.");
  }
};
var shared = null;
function defaultStore() {
  if (shared) return shared;
  const url = process.env.UPSTASH_REDIS_REST_URL ?? process.env.KV_REST_API_URL;
  const token = process.env.UPSTASH_REDIS_REST_TOKEN ?? process.env.KV_REST_API_TOKEN;
  shared = url && token ? new RedisStore(url, token) : new MemoryStore();
  return shared;
}

// functions/stats.ts
async function handler(req, res) {
  res.setHeader("Cache-Control", "no-store");
  if (req.method !== "GET") return res.status(405).json({ ok: false, error: "Use GET." });
  if (!isAdmin(req.headers.authorization, process.env.FEEDBACK_ADMIN_KEY)) return res.status(403).json({ ok: false, error: "Not allowed." });
  try {
    const records = await defaultStore().listGames(5e3);
    return res.status(200).json({ ok: true, stats: aggregate(records), recent: records.slice(-20).reverse() });
  } catch (e) {
    return res.status(500).json({ ok: false, error: e instanceof Error ? e.message : "Server error." });
  }
}
module.exports = module.exports.default;
